### ISSUE TITLE
add info on where the task is running

### ISSUE THREAD

**Issue by dsschult** [WIPACrepo/iceprod#146]
We have the ability to inject which condor job is running a task, and where the submit directory is located:

```
dschultz@node017 /scratch/condor/dir_7923 $ grep '^ClusterId\|ProcId\|OrigIwd' .job.ad                             
ProcId = 1
ClusterId = 69409
OrigIwd = "/mnt/scratch/simprod/iceprod2_fullsource/submit/pilot_136647"
```

Of course, I've successfully avoided adding any code that knows about HTCondor to the pilot.  Currently it is system-agnostic.  This would break that pattern.

So, is this information useful enough for debugging to override our principles?  Or have we determined that we'll always run on top of HTCondor?

**Comment by dsschult** [comment]
We can also inject task_ids into the job classad.  Something to think about.

**Comment by gonzalomerino** [comment]
I think our current model of "one central htcondor pool" is quite well established so it would be justified to add some "htcondor specific" code in iceprod2.

We certainly do not want to modify iceprod2 so that it only runs on htcondor, but given our current setup, and the one for the foreseeable future, I think it will be a big advantage that the iceprod pilots are able to provide some htcondor specific traceability.

if the above htcondor job values are available, a pilot could then inject them. If they are not found, do nothing as now. 

what are you thinking about when you say "inject"? will this be some iceprod2 specific metric? or graphite? or adding the info to the job classad with condor_chirp?

**Comment by dsschult** [comment]
Clarifying "inject":

- can add the condor job info to the iceprod db for each task (iceprod-specific)
- can add the task info to the condor job (condor_chirp)

**Comment by gonzalomerino** [comment]
For option 1 "add the condor job info to the iceprod db for each task", this would be adding some of those htcondor specific numbers to the json blob that jobs send back to iceprod2 once they finish. Correct?

If you think that might be not a lot of effort, I would go for that. We know that then we still need to have some mechanism to extract those json blobs and put them in an ES or something to analyze them, but at least we will be one step closer...

**Comment by dsschult** [comment]
Since we switched to submitting tasks to condor, I've added iceprod classads in the condor jobs.
